# Basic bioinformatics

The next chapters focus on the analysis of molecular sequence data using the command line. 
Nothing too fancy, just some basic commands to look at the data files and summarize information from the sequences.

## Section 1: Basic commands for sequence data

### Downloading the datasets

We are going to use two main datasets:

```
https://raw.githubusercontent.com/Tabima/BIOL123/master/Lab_3/AAB21188.seq
https://raw.githubusercontent.com/Tabima/BIOL123/master/Lab_3/S79522.seq
```

1. Create a folder called `Lab_3` in your home folder at the cluster
2. Download the files. Answer the following question:


```{block, type='rmdquestion'}
### Question 1

-  What commands did you use to download the files?
```

3. Check the files. Answer the following questions:


```{block, type='rmdquestion'}
### Question 2

- What kind of sequence (DNA/RNA/Protein) is the `S79522.seq` file? Add the command you used to answer the question.
``` 

```{block, type='rmdquestion'}
### Question 3

- What kind of sequence (DNA/RNA/Protein) is the `AAB21188.seq` file? Add the command you used to answer the question.
```

***

### Counting basic patterns for DNA data

Ok, after checking the files we know now that the `S79522.seq` file contains a DNA sequence. 

Let's do some command line exercises with it. Answer all of these questions:

```{block, type='rmdquestion'}
### Question 4

- How many lines are found on this file?
```


```{block, type='rmdquestion'}
### Question 5

- How many characters are found on this file? (Or, what is the length of this sequence?)
```

```{block, type='rmdquestion'}
### Question 6

- How many A, C, G, and T can you find in this sequence?
```

```{block, type='rmdquestion'}
### Question 7

- Convert this sequence to RNA and save it in a file called `S79522_RNA.seq`. Please add the command you used to create the file. (Don't create a complementary strand, just convert this one from DNA to RNA)
```

```{block, type='rmdquestion'}
### Question 8

- How can we test that this new file is an RNA sequence `S79522_RNA.seq`. Please add a command you'd use to check if this is DNA or RNA.
```

```{block, type='rmdquestion'}
### Question 9

- Finally, using your RNA sequence, check how many start codons (`AUG`) or stop codons (`UAA`,`UAG`, or `UGA`) may exist in your sequence
```

***

### Counting basic patterns for Amino Acid data

Ok, after checking the files we know now that the `AAB21188.seq` file contains an amino acid sequence. 

```{block, type='rmdquestion'}
### Question 10

- How many characters are found on this file? (Or, what is the length of this sequence?)
```

```{block, type='rmdquestion'}
### Question 11

- Select two amino acids of interest and count them. Please add the command used to count them.
```


We have four candidate patterns for this gene:

 - `VLKYYKVD` (A common pattern found in the Ribosomal S27 subunit domains)
 - `ITLEVE` (A common pattern found in Ubiquitin domains)
 - `KWCPRP` (A common pattern found in In Between Ring fingers (IBR) domains)
 - `LSVLSQKM`  (A common pattern found in DNA polymerase unit A domains)
 
```{block, type='rmdquestion'}
### Question 12  
 Which patterns do you find in the sequence? Fill in this table:
 
|Sequence|Ribosomal 27|Ubiquitin|IBR|DNA poly A|
|---|---|---|---|---|
|AAB21188|Yes/No|Yes/No|Yes/No|Yes/No|
 
```
 
*** 

## Section 2: Creating pipelines

In this section we will learn something new and exciting: 

We will make a simple pipeline to automate counting nucleotide sequences.

### What is a pipeline?

Pipelines are **sequential lines of code that can be used to use multiple commands at once**.

For example, if you want to count all the `U` in a DNA sequence that you have transformed into DNA, you can actually do this in one simple line of code.

Think about this as a logical set of steps (or, a *pseudocode*):

1. Read the DNA file
2. Replace the `T` for `U`
3. Extract the matches to `U`
4. Count those matches

Using the command line the instructions would be like:
 
 ```
 cat file.txt
 sed 's/T/U/g' file.txt > file_rna.txt
 grep -o U file_rna.txt > U_ocurrences.txt
 wc -l U_ocurrences.txt
 ```
 
This code works, but it's quite useless as it forces us to create two independent files: `file_rna.txt` and `U_ocurrences.txt`. 
 
Imagine that the output of these files were large and you had no space left in your hard drive! You would have to run everything again from the beginning!
 
One of the options is to use pipelines, using the **pipe (`|`) modifier**. This modifier works as an "and then". 
 
So for example, a command that is like this: `ls -lrt | grep seq | wc -l` can be read as:
 
Make a list of all the files **and then** extract all the matches to `seq` **and then** count the number of occurrences.
 
 So, we can totally use this with our data.
 
#### Pipeline example using DNA data
 
Before we start, let me introduce you to two elements: 

1. Variables
2. the `echo` command.

##### Variables

Variables can be defined as **a place to temporarily store a piece of information**.

For example, your wallet is a variable that is full of your money. 

So, if you have $10 in your wallet, then your variable is:

```{bash}
wallet=10
```

So, that is how you define a variable in `bash`. To see what the value of that variable is, you use the `echo` command
 
##### The `echo` command

The `echo` command will print to your screen whatever you tell it to print. 

For example, if you tell the command to `echo 'hello'`, this will happen:

```{bash}
echo 'hello'
```

Meaning that you can tell it to say whatever you want to say. If you want to add spaces or other weird characters, make sure you surround the statement with single quotes

```{bash}
echo 'This is the best course ever'
```

##### Mixing variables and `echo`

So, we want to mix these two because then you can store a variable and print it in the screen, for example:

```{bash}
statement='This is the best course ever'
echo $statement
```

Look at this! You can simplify the instructions and print variables!

Now, did you notice that the variable `statement` had a `$` in front? That is how you tell `bash` that you are using a variable!

If you don't add it this is what happens:

```{bash}
echo statement
```

So, you are just printing the word statement. Interesting, right?

#### Using a pipeline as an example of variables and pipes

Now, let's say we want to count all the nucleotides in our DNA file independently. 

So, we want to extract each nucleotide, starting from the `A`, using `grep -c A`, and then counting lines with `wc -l`:

```{bash}
grep -o A Lab_3/S79522.seq | wc -l
```

```{block, type='rmdquestion'}
### Question 13

- Did these results match what you did at the beginning of the lab? Expand briefly your answer.
```


Ok, now, to save this on a variable (you can call the variable anything as long as it doesn't have any spaces or weird characters) we just put the entire pipeline inside a `$()`, like this:

```{bash}
nucA=$(grep -o A Lab_3/S79522.seq | wc -l)
echo $nucA
```

Wow! That was easy!

Now, if you want to add more variables you can do it like this:

```{bash}
nucA=$(grep -o A Lab_3/S79522.seq | wc -l)
nucC=$(grep -o C Lab_3/S79522.seq | wc -l)

echo 'Number of A:'$nucA
echo 'Number of C:'$nucC
```

Answer the following questions, please:

```{block, type='rmdquestion'}
### Question 14

- How would you count the other nucleotides? Add the code below:
```


```{block, type='rmdquestion'}
### Question 15 

- Write a set of instructions to count ten of the amino acids in the `AAB21188.seq` file. 
```


***

## Section 3: Processing local files into the cluster

So, we know how to download files from different sources into the cluster. Today, we are going to learn how to move files from and to the cluster.


1. Download the `sequence_1` and `sequence_2` files from Moodle.

2. Create a new folder called `mystery_genes` in your `Lab_3` folder

3. Upload the files into the folder

4. Check if the files are there. 

```{block, type='rmdquestion'}
### Question 16

- How did you check if the files were correctly uploaded?
```

### Checking file types

If you remember, we saw some file types for sequence data in the theory class. These are `FASTA` and `GenBank`. 

We are going to deal with these files today, and see how we can extract important information from these files.

```{block, type='rmdquestion'}
### Question 17

- Briefly summarize what a FASTA file is and what a GenBank file is (one sentence each)
```

```{block, type='rmdquestion'}
### Question 18

- Can these formats include RNA, DNA and Aminoacid data? (Yes/No answer)
```

Now, use your knowledge of the command line to answer these questions:

```{block, type='rmdquestion'}
### Question 19

- What format is the `sequence_1` file in? (FASTA or GenBank) Briefly explain your answer.
- What format is the `sequence_2` file in? (FASTA or GenBank) Briefly explain your answer.
```

If you answered correctly, you have seen that `sequence_1` is in FASTA format, while `sequence_2` is in GenBank format.

### FASTA: Data handling

```{block, type='rmdquestion'}
### Question 20

- How many lines does the `sequence_1` file have?
- How can you count the number of SEQUENCES that exist in the `sequence_1` file? 
- What is the number of sequences in the `sequence_1` file? Is this result different than the number of lines in the file? Why? 
```

Now, we know that the number of sequences (five) can be recognized by counting the number of `>` symbols in the sequence, right? 

This means that for this particular FASTA file, you can extract each sequence individually if you know the lines. 

For example:
- lines 1 and 2 have the first sequence
- lines 3 and 4 have the second

and so on.

That means we can extract each sequence. You can do this using the `sed` command in the following way

```bash
sed -n 'starting_line,ending_line p' file_with_sequences
```

So, for example, to extract the first sequence in FASTA format:

```bash
sed -n '1,2 p' sequence_1
```

Now, because we are extracting from a FASTA file, you will get the header and the sequence data. To only see the sequence data, use `grep` to extract all lines that DON'T have a `>` symbol. You can pipe the results of `sed` into `grep`!

```bash
sed -n '1,2 p' sequence_1 | grep -v ">" 
```

In this case, we had to put the `>` symbol between quotes, because without them the command line interprets it as a redirect and creates a new file.

Finally, we can even count the length of the sequence:

```bash
sed -n '1,2 p' sequence_1 | grep -v ">" | wc -c 
```

This first sequence is 7478 nucleotides long! Ain't this cool?


```{block, type='rmdquestion'}
### Question 21
- How can you save the new sequence in a new FASTA file?
- Extract all other sequences from the file and save them in 5 different FASTA files. Add the code you used below
```

***

```{block, type='rmdalert'}
## STOP HERE!

We will learn about how to write a script to answer the take home HW. On the meantime, finish the Section 4 questions
```


```{block, type='rmdquestion'}
## Take Home HW

Can you create code that will do the following for each extracted FASTA sequence?

1. Count the number of A,G,C and T?
2. Count the length of each sequence?
3. Count the number of open reading frames (ORF)?

Present the code and the results
```

***

## Section 4: GenBank Files

GenBank files are more complex than FASTA files. 

1. These files are quite complex to analyze using only the command line. However, we can take a look a this data and answer a simple question using the command line:

```{block, type='rmdquestion'}
### Question 22

- How many lines does the `sequence_2` file have?
```

2. Open the file using `less -NS` and answer the following questions:

```{block, type='rmdquestion'}
### Question 23

- If you were looking for the information on the gene that codes for `lacZ`, what line would you use?
- What species is this gene taken from?
- What genomic region does this represent? 
- How many other genes can you find?
```

```{block, type='rmdquestion'}
### Question 24

Genic regions on GenBank files are represented by three different types: `mRNA`, `gene`, `CDS`. 

- What are the differences between these `mRNA`, `gene`, and `CDS` based in your GenBank and the NCBI help?
```

***

## For loops and Solution to the HW

1. Extracting all the sequences from `sequence_1` into different files (As asked in Question 21)

We have noticed that
- Gene 1 is in lines one and two

```{bash}
sed -n '1,2 p' sequence_1 > gene_1.fasta
cat gene_1.fasta
```


- Gene 2 is in lines three and four

```{bash}
sed -n '3,4 p' sequence_1 > gene_2.fasta
cat gene_2.fasta
```

- Gene 3 is in lines five and six

```{bash}
sed -n '5,6 p' sequence_1 > gene_3.fasta
cat gene_3.fasta
```

- Gene 4 is in lines seven and eight

```{bash}
sed -n '7,8 p' sequence_1 > gene_4.fasta
cat gene_4.fasta
```

- Gene 5 is in lines nine and ten

```{bash}
sed -n '9,10 p' sequence_1 > gene_5.fasta
cat gene_5.fasta
```

2. Recall what the homework asked: create code that will do the following for **each extracted FASTA sequence**:

- Count the number of A,G,C and T?

```{bash}
# Number of A
grep -v ">" gene_1.fasta | grep -o "A" | wc -l
grep -v ">" gene_2.fasta | grep -o "A" | wc -l
grep -v ">" gene_3.fasta | grep -o "A" | wc -l
grep -v ">" gene_4.fasta | grep -o "A" | wc -l
grep -v ">" gene_5.fasta | grep -o "A" | wc -l
```

In this case, because the command `grep -v ">" VARIABLE | grep -o "A" | wc -l` is the same, the only thing that changes (**THE VARIABLE**) is the gene name

### How do we fill up variables?

What is the variable? A list of the files of interest. What do all these files have in common?

1. They start with the word `gene`
2. They end with the word `.fasta`

So, what this means, is that we can create a list of these elements that have things in common!

```{bash}
ls Lab_3/mystery_genes
```

A wildcard (`*`: means ANYTHING) allows you to select something that has a matching pattern with a variable:

1. They start with the word `gene`: `gene*`

```{bash}
ls gene*
```

2. They end with the word `.fasta`: `*.fasta`

```{bash}
ls *.fasta
```

You can put them on a list with any name. In this case, the variable name will be `seqfile`:

```{bash}
seqfile=$(ls *.fasta)
echo $seqfile
```

Now, you want to do a simple `for loop`:

```
FOR EACH ELEMENT IN VARIABLE_LIST;
  DO COMMAND;
  END
```

You command is to say "The gene file is: `$VARIABLE`". The `$` means EACH element of the variable list called `$seqfile`

```{bash}
for seqfile in *.fasta;
  do
  echo "The gene file is: $seqfile"
  done
```

Now that we know how a loop works, we can use real commands:

- Let's count the number of A's

```{bash}
for seqfile in *.fasta;
  do
  seqname=$(grep ">" $seqfile)
  echo "Sequence in progress: $seqname"
  numA=$(grep -v ">" $seqfile | grep -o "A" | wc -l)
  echo "The number of A's in: $numA"
  numC=$(grep -v ">" $seqfile | grep -o "C" | wc -l)
  echo "The number of C's is: $numC"
  numT=$(grep -v ">" $seqfile | grep -o "T" | wc -l)
  echo "The number of T's is: $numT"
  numG=$(grep -v ">" $seqfile | grep -o "G" | wc -l)
  echo "The number of G's is: $numG"
  echo "End of sequence $seqname"
  echo
  done
```

### Complete, for extra points if desired:

- Count the length of each sequence?
- Count the number of open reading frames (ORF)? 

