---
title: "BASH example"
output: html_notebook
---

1. Extracting all the sequences from `sequence_1` into different files (As asked in Question 21)

We have noticed that
- Gene 1 is in lines one and two

```{bash}
sed -n '1,2 p' sequence_1 > gene_1.fasta
cat gene_1.fasta
```


- Gene 2 is in lines three and four

```{bash}
sed -n '3,4 p' sequence_1 > gene_2.fasta
cat gene_2.fasta
```

- Gene 3 is in lines five and six

```{bash}
sed -n '5,6 p' sequence_1 > gene_3.fasta
cat gene_3.fasta
```

- Gene 4 is in lines seven and eight

```{bash}
sed -n '7,8 p' sequence_1 > gene_4.fasta
cat gene_4.fasta
```

- Gene 5 is in lines nine and ten

```{bash}
sed -n '9,10 p' sequence_1 > gene_5.fasta
cat gene_5.fasta
```

2. The homework said:  Can you create code that will do the following for **each extracted FASTA sequence?**

- Count the number of A,G,C and T?

```{bash}
# Number of A
grep -v ">" gene_1.fasta | grep -o "A" | wc -l
grep -v ">" gene_2.fasta | grep -o "A" | wc -l
grep -v ">" gene_3.fasta | grep -o "A" | wc -l
grep -v ">" gene_4.fasta | grep -o "A" | wc -l
grep -v ">" gene_5.fasta | grep -o "A" | wc -l
```

In this case, because the command `grep -v ">" VARIABLE | grep -o "A" | wc -l` is the same, the only thing that changes (**THE VARIABLE**) is the gene name

## How do we fill up variables?

What is the variable? A list of the files of interest. What do all these files have in common?

1. They start with the word `gene`
2. They end with the word `.fasta`

So, what this means, is that we can create a list of these elements that have things in common!

```{bash}
ls
```

A wildcard (`*`: means ANYTHING) allows you to select something that has a matching pattern with a variable:

1. They start with the word `gene`: `gene*`

```{bash}
ls gene*
```

2. They end with the word `.fasta`" `*.fasta`

```{bash}
ls *.fasta
```

You can put them on a list with any name. In this case, the variable name will be `seqfile`:

```{bash}
seqfile=$(ls *.fasta)
echo $seqfile
```

Now, you want to do a simple `for loop`:

```
FOR EACH ELEMENT IN VARIABLE_LIST;
  DO COMMAND;
  END
```

You command is to say "The gene file is: `$VARIABLE`". The `$` means EACH element of the variable list called `$seqfile`

```{bash}
for seqfile in *.fasta;
  do
  echo "The gene file is: $seqfile"
  done
```

Now that we know how a loop works, we can use real commands:

- Lets count the number of A's

```{bash}
for seqfile in *.fasta;
  do
  seqname=$(grep ">" $seqfile)
  echo "Sequence in progress: $seqname"
  numA=$(grep -v ">" $seqfile | grep -o "A" | wc -l)
  echo "The number of A's in: $numA"
  numC=$(grep -v ">" $seqfile | grep -o "C" | wc -l)
  echo "The number of C's is: $numC"
  numT=$(grep -v ">" $seqfile | grep -o "T" | wc -l)
  echo "The number of T's is: $numT"
  numG=$(grep -v ">" $seqfile | grep -o "G" | wc -l)
  echo "The number of G's is: $numG"
  echo "End of sequence $seqname"
  echo
  done
```
## How do we do this:

- Count the length of each sequence?
- Count the number of open reading frames (ORF)? 



